@startuml classes_pit-box
set namespaceSeparator none
class "<color:red>ExportError</color>" as export_remote_desktop_password_to_keepass.ExportError {
}
class "Handler" as pit_box_api.Handler {
  do_DELETE()
  do_GET()
  {abstract}log_message()
}
class "<color:red>ResolveError</color>" as resolve_remote_desktop_password.ResolveError {
}
@enduml
